### ISSUE TITLE
Registration error

### ISSUE THREAD

**Issue by rocky517** [Plexis/Plexis#4]
Just installed it, and I got the following when a user tries to register:

PHP Error

Message: class_init_failed

Reporting File: /www/system/core/Common.php
Line: 103

**Comment by clarajk** [comment]
Sounds like an issue on your end, is there any more information you can provide to help reproduce the error? Such as Apache modules, PHP extensions, exact PHP version/PHP version id (perhaps the issue is a result of a bug in the Zend engine for your PHP build), or any outstanding php.ini settings. Providing the debug_account-register.xml file from <Plexis Dir>/system/logs/debug/ at time of the error may also help find out what went wrong. From what I can see on my end everything is running smoothly and I've been unable to reproduce either issue.

**Comment by rocky517** [comment]
Here's a phpinfo() from my server, see if you can figure anything out..
http://filebeam.com/aae4879805fa33f735efb3e3f3f381fa

Regarding the configuration, everything is pretty much default; except the "a2enmod rewrite" I had ran.
Can't the /system/logs/debug/ dir, perhaps you can assist?\* Maybe you can pm me with an IM address, so I can do the linux Q&A for you ;)

[EDIT] *Maybe this is what you requested? http://filebeam.com/45caa97f7808d5e0a2345a0c931ca8ac
